# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_window.ui'
##
## Created by: Qt User Interface Compiler version 6.8.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QLayout, QLineEdit, QMainWindow, QMenuBar,
    QPushButton, QScrollArea, QSizePolicy, QStatusBar,
    QTabWidget, QVBoxLayout, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(978, 1011)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.user_clicker = QTabWidget(self.centralwidget)
        self.user_clicker.setObjectName(u"user_clicker")
        self.user_clicker.setEnabled(True)
        self.user_clicker.setGeometry(QRect(0, -1, 981, 1001))
        font = QFont()
        font.setPointSize(18)
        font.setBold(True)
        self.user_clicker.setFont(font)
        self.user_clicker.setAutoFillBackground(False)
        self.user_clicker.setTabPosition(QTabWidget.TabPosition.North)
        self.user_clicker.setTabShape(QTabWidget.TabShape.Rounded)
        self.clicker = QWidget()
        self.clicker.setObjectName(u"clicker")
        self.clicker.setFont(font)
        self.clicks_amount = QLineEdit(self.clicker)
        self.clicks_amount.setObjectName(u"clicks_amount")
        self.clicks_amount.setGeometry(QRect(260, 120, 241, 71))
        self.clicks_amount.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.clicks_amount.setFrame(True)
        self.clicks_amount.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.clicks_amount.setReadOnly(True)
        self.clicks_amount.setClearButtonEnabled(False)
        self.click_button = QPushButton(self.clicker)
        self.click_button.setObjectName(u"click_button")
        self.click_button.setGeometry(QRect(300, 230, 171, 161))
        self.user_clicker.addTab(self.clicker, "")
        self.magazin = QWidget()
        self.magazin.setObjectName(u"magazin")
        self.buy_scroll = QScrollArea(self.magazin)
        self.buy_scroll.setObjectName(u"buy_scroll")
        self.buy_scroll.setGeometry(QRect(0, -10, 881, 591))
        self.buy_scroll.setWidgetResizable(True)
        self.buy_widget_scroll = QWidget()
        self.buy_widget_scroll.setObjectName(u"buy_widget_scroll")
        self.buy_widget_scroll.setGeometry(QRect(0, 0, 879, 589))
        self.gridLayoutWidget = QWidget(self.buy_widget_scroll)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(10, 10, 821, 261))
        self.buy_layout = QGridLayout(self.gridLayoutWidget)
        self.buy_layout.setSpacing(2)
        self.buy_layout.setObjectName(u"buy_layout")
        self.buy_layout.setSizeConstraint(QLayout.SizeConstraint.SetNoConstraint)
        self.buy_layout.setContentsMargins(0, 0, 0, 0)
        self.eul = QWidget(self.gridLayoutWidget)
        self.eul.setObjectName(u"eul")
        self.eul.setMinimumSize(QSize(390, 0))
        self.eul.setMaximumSize(QSize(375, 110))
        self.eul.setStyleSheet(u"background-color: rgb(81, 81, 81)")
        self.horizontalLayoutWidget_15 = QWidget(self.eul)
        self.horizontalLayoutWidget_15.setObjectName(u"horizontalLayoutWidget_15")
        self.horizontalLayoutWidget_15.setGeometry(QRect(0, 0, 391, 111))
        self.eul_hlayout = QHBoxLayout(self.horizontalLayoutWidget_15)
        self.eul_hlayout.setObjectName(u"eul_hlayout")
        self.eul_hlayout.setContentsMargins(5, 0, 0, 0)
        self.eul_pic = QLabel(self.horizontalLayoutWidget_15)
        self.eul_pic.setObjectName(u"eul_pic")
        self.eul_pic.setMaximumSize(QSize(95, 95))
        self.eul_pic.setTextFormat(Qt.TextFormat.PlainText)
        self.eul_pic.setPixmap(QPixmap(u"../eul.png"))
        self.eul_pic.setScaledContents(True)
        self.eul_pic.setOpenExternalLinks(True)

        self.eul_hlayout.addWidget(self.eul_pic)

        self.eul_vlayout = QVBoxLayout()
        self.eul_vlayout.setObjectName(u"eul_vlayout")
        self.eul_name = QLabel(self.horizontalLayoutWidget_15)
        self.eul_name.setObjectName(u"eul_name")
        self.eul_name.setFont(font)

        self.eul_vlayout.addWidget(self.eul_name)

        self.eul_desc = QLabel(self.horizontalLayoutWidget_15)
        self.eul_desc.setObjectName(u"eul_desc")
        font1 = QFont()
        font1.setPointSize(14)
        font1.setBold(False)
        self.eul_desc.setFont(font1)

        self.eul_vlayout.addWidget(self.eul_desc)

        self.eul_button = QPushButton(self.horizontalLayoutWidget_15)
        self.eul_button.setObjectName(u"eul_button")
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        self.eul_button.setFont(font2)

        self.eul_vlayout.addWidget(self.eul_button)


        self.eul_hlayout.addLayout(self.eul_vlayout)


        self.buy_layout.addWidget(self.eul, 0, 1, 1, 1)

        self.bkb = QWidget(self.gridLayoutWidget)
        self.bkb.setObjectName(u"bkb")
        self.bkb.setMinimumSize(QSize(390, 0))
        self.bkb.setMaximumSize(QSize(390, 110))
        self.bkb.setStyleSheet(u"background-color: rgb(81, 81, 81)")
        self.horizontalLayoutWidget_16 = QWidget(self.bkb)
        self.horizontalLayoutWidget_16.setObjectName(u"horizontalLayoutWidget_16")
        self.horizontalLayoutWidget_16.setGeometry(QRect(0, 0, 391, 111))
        self.bkb_hlayout = QHBoxLayout(self.horizontalLayoutWidget_16)
        self.bkb_hlayout.setObjectName(u"bkb_hlayout")
        self.bkb_hlayout.setContentsMargins(5, 0, 0, 0)
        self.bkb_pic = QLabel(self.horizontalLayoutWidget_16)
        self.bkb_pic.setObjectName(u"bkb_pic")
        self.bkb_pic.setMaximumSize(QSize(95, 95))
        self.bkb_pic.setTextFormat(Qt.TextFormat.PlainText)
        self.bkb_pic.setPixmap(QPixmap(u"../../../OneDrive/Desktop/bkb.png"))
        self.bkb_pic.setScaledContents(True)
        self.bkb_pic.setOpenExternalLinks(True)

        self.bkb_hlayout.addWidget(self.bkb_pic)

        self.bkb_vlayout = QVBoxLayout()
        self.bkb_vlayout.setObjectName(u"bkb_vlayout")
        self.bkb_name = QLabel(self.horizontalLayoutWidget_16)
        self.bkb_name.setObjectName(u"bkb_name")
        self.bkb_name.setFont(font)

        self.bkb_vlayout.addWidget(self.bkb_name)

        self.bkb_desc = QLabel(self.horizontalLayoutWidget_16)
        self.bkb_desc.setObjectName(u"bkb_desc")
        self.bkb_desc.setFont(font1)

        self.bkb_vlayout.addWidget(self.bkb_desc)

        self.bkb_button = QPushButton(self.horizontalLayoutWidget_16)
        self.bkb_button.setObjectName(u"bkb_button")
        self.bkb_button.setFont(font2)

        self.bkb_vlayout.addWidget(self.bkb_button)


        self.bkb_hlayout.addLayout(self.bkb_vlayout)


        self.buy_layout.addWidget(self.bkb, 1, 1, 1, 1)

        self.bottle = QWidget(self.gridLayoutWidget)
        self.bottle.setObjectName(u"bottle")
        self.bottle.setMinimumSize(QSize(390, 0))
        self.bottle.setMaximumSize(QSize(375, 110))
        self.bottle.setStyleSheet(u"background-color: rgb(81, 81, 81)")
        self.horizontalLayoutWidget_13 = QWidget(self.bottle)
        self.horizontalLayoutWidget_13.setObjectName(u"horizontalLayoutWidget_13")
        self.horizontalLayoutWidget_13.setGeometry(QRect(0, 0, 391, 111))
        self.bottle_hlayout = QHBoxLayout(self.horizontalLayoutWidget_13)
        self.bottle_hlayout.setObjectName(u"bottle_hlayout")
        self.bottle_hlayout.setContentsMargins(5, 0, 0, 0)
        self.bottle_pic_11 = QLabel(self.horizontalLayoutWidget_13)
        self.bottle_pic_11.setObjectName(u"bottle_pic_11")
        self.bottle_pic_11.setMaximumSize(QSize(95, 95))
        self.bottle_pic_11.setTextFormat(Qt.TextFormat.PlainText)
        self.bottle_pic_11.setPixmap(QPixmap(u"../bottle.png"))
        self.bottle_pic_11.setScaledContents(True)
        self.bottle_pic_11.setOpenExternalLinks(True)

        self.bottle_hlayout.addWidget(self.bottle_pic_11)

        self.bottle_vlayout = QVBoxLayout()
        self.bottle_vlayout.setObjectName(u"bottle_vlayout")
        self.bottle_name_11 = QLabel(self.horizontalLayoutWidget_13)
        self.bottle_name_11.setObjectName(u"bottle_name_11")
        self.bottle_name_11.setFont(font)

        self.bottle_vlayout.addWidget(self.bottle_name_11)

        self.bottle_desc = QLabel(self.horizontalLayoutWidget_13)
        self.bottle_desc.setObjectName(u"bottle_desc")
        self.bottle_desc.setFont(font1)

        self.bottle_vlayout.addWidget(self.bottle_desc)

        self.bottle_button = QPushButton(self.horizontalLayoutWidget_13)
        self.bottle_button.setObjectName(u"bottle_button")
        self.bottle_button.setFont(font2)

        self.bottle_vlayout.addWidget(self.bottle_button)


        self.bottle_hlayout.addLayout(self.bottle_vlayout)


        self.buy_layout.addWidget(self.bottle, 0, 0, 1, 1)

        self.blink = QWidget(self.gridLayoutWidget)
        self.blink.setObjectName(u"blink")
        self.blink.setMinimumSize(QSize(390, 0))
        self.blink.setMaximumSize(QSize(375, 110))
        self.blink.setStyleSheet(u"background-color: rgb(81, 81, 81)")
        self.horizontalLayoutWidget_2 = QWidget(self.blink)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(0, 0, 391, 111))
        self.blink_hlayout = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.blink_hlayout.setObjectName(u"blink_hlayout")
        self.blink_hlayout.setContentsMargins(5, 0, 0, 0)
        self.blink_pic = QLabel(self.horizontalLayoutWidget_2)
        self.blink_pic.setObjectName(u"blink_pic")
        self.blink_pic.setMaximumSize(QSize(95, 95))
        self.blink_pic.setTextFormat(Qt.TextFormat.PlainText)
        self.blink_pic.setPixmap(QPixmap(u"../../../OneDrive/Desktop/Blink.png"))
        self.blink_pic.setScaledContents(True)
        self.blink_pic.setOpenExternalLinks(True)

        self.blink_hlayout.addWidget(self.blink_pic)

        self.blink_vhayot = QVBoxLayout()
        self.blink_vhayot.setObjectName(u"blink_vhayot")
        self.blink_name = QLabel(self.horizontalLayoutWidget_2)
        self.blink_name.setObjectName(u"blink_name")
        self.blink_name.setFont(font)

        self.blink_vhayot.addWidget(self.blink_name)

        self.blink_desc = QLabel(self.horizontalLayoutWidget_2)
        self.blink_desc.setObjectName(u"blink_desc")
        self.blink_desc.setFont(font1)

        self.blink_vhayot.addWidget(self.blink_desc)

        self.blink_button = QPushButton(self.horizontalLayoutWidget_2)
        self.blink_button.setObjectName(u"blink_button")
        self.blink_button.setFont(font2)

        self.blink_vhayot.addWidget(self.blink_button)


        self.blink_hlayout.addLayout(self.blink_vhayot)


        self.buy_layout.addWidget(self.blink, 1, 0, 1, 1)

        self.buy_scroll.setWidget(self.buy_widget_scroll)
        self.user_clicker.addTab(self.magazin, "")
        self.user = QWidget()
        self.user.setObjectName(u"user")
        self.scrollArea = QScrollArea(self.user)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(10, 10, 951, 461))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 949, 459))
        self.verticalLayoutWidget = QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(9, 9, 16777215, 441))
        self.layout_scroll = QVBoxLayout(self.verticalLayoutWidget)
        self.layout_scroll.setObjectName(u"layout_scroll")
        self.layout_scroll.setContentsMargins(0, 0, 0, 0)
        self.description = QWidget(self.verticalLayoutWidget)
        self.description.setObjectName(u"description")
        self.description.setMinimumSize(QSize(0, 60))
        self.description.setMaximumSize(QSize(16777215, 60))
        self.description.setStyleSheet(u"background-color: rgb(77, 77, 77)")
        self.horizontalLayoutWidget = QWidget(self.description)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(-1, -3, 931, 61))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.label_3 = QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setFont(font2)
        self.label_3.setTextFormat(Qt.TextFormat.AutoText)
        self.label_3.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label_3)

        self.label_2 = QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setFont(font2)
        self.label_2.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label_2)

        self.label = QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName(u"label")
        self.label.setFont(font2)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label)

        self.label_4 = QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setFont(font2)
        self.label_4.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout.addWidget(self.label_4)


        self.layout_scroll.addWidget(self.description)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.user_clicker.addTab(self.user, "")
        self.admin_window = QTabWidget(self.centralwidget)
        self.admin_window.setObjectName(u"admin_window")
        self.admin_window.setEnabled(True)
        self.admin_window.setGeometry(QRect(0, -1, 981, 1001))
        self.admin_window.setFont(font)
        self.admin_window.setTabShape(QTabWidget.TabShape.Rounded)
        self.admin_window.setElideMode(Qt.TextElideMode.ElideNone)
        self.admin_window.setUsesScrollButtons(True)
        self.admin_window.setDocumentMode(False)
        self.admin_window.setTabsClosable(False)
        self.admin_window.setTabBarAutoHide(False)
        self.general_stats = QWidget()
        self.general_stats.setObjectName(u"general_stats")
        self.users_amount = QWidget(self.general_stats)
        self.users_amount.setObjectName(u"users_amount")
        self.users_amount.setGeometry(QRect(10, 10, 230, 150))
        self.users_amount.setMaximumSize(QSize(230, 150))
        self.users_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_17 = QLabel(self.users_amount)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(0, 0, 231, 30))
        font3 = QFont()
        font3.setPointSize(16)
        font3.setBold(False)
        self.label_17.setFont(font3)
        self.label_17.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_17.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.us_amount = QLabel(self.users_amount)
        self.us_amount.setObjectName(u"us_amount")
        self.us_amount.setGeometry(QRect(8, 35, 211, 81))
        font4 = QFont()
        font4.setPointSize(18)
        font4.setBold(False)
        self.us_amount.setFont(font4)
        self.us_amount.setStyleSheet(u"border: 0px")
        self.us_amount.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graf_users = QPushButton(self.users_amount)
        self.graf_users.setObjectName(u"graf_users")
        self.graf_users.setGeometry(QRect(40, 120, 151, 24))
        self.graf_users.setStyleSheet(u"background-color: rgb(24, 24, 24)")
        self.pure_clicks = QWidget(self.general_stats)
        self.pure_clicks.setObjectName(u"pure_clicks")
        self.pure_clicks.setGeometry(QRect(270, 10, 230, 150))
        self.pure_clicks.setMaximumSize(QSize(230, 150))
        self.pure_clicks.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_19 = QLabel(self.pure_clicks)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(0, 0, 231, 30))
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_19.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.pure_clicks_amount = QLabel(self.pure_clicks)
        self.pure_clicks_amount.setObjectName(u"pure_clicks_amount")
        self.pure_clicks_amount.setGeometry(QRect(8, 35, 211, 111))
        self.pure_clicks_amount.setFont(font4)
        self.pure_clicks_amount.setStyleSheet(u"border: 0px\n"
"")
        self.pure_clicks_amount.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.online = QWidget(self.general_stats)
        self.online.setObjectName(u"online")
        self.online.setGeometry(QRect(10, 170, 230, 150))
        self.online.setMaximumSize(QSize(230, 150))
        self.online.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_21 = QLabel(self.online)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(0, 0, 231, 30))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_21.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.now_online = QLabel(self.online)
        self.now_online.setObjectName(u"now_online")
        self.now_online.setGeometry(QRect(8, 35, 211, 81))
        self.now_online.setFont(font4)
        self.now_online.setStyleSheet(u"border: 0px")
        self.now_online.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graf_online = QPushButton(self.online)
        self.graf_online.setObjectName(u"graf_online")
        self.graf_online.setGeometry(QRect(40, 120, 151, 24))
        self.graf_online.setStyleSheet(u"background-color: rgb(24, 24, 24)")
        self.widget_6 = QWidget(self.general_stats)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(10, 330, 230, 150))
        self.widget_6.setMaximumSize(QSize(230, 150))
        self.widget_6.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.avg_session = QLabel(self.widget_6)
        self.avg_session.setObjectName(u"avg_session")
        self.avg_session.setGeometry(QRect(0, 0, 231, 30))
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(False)
        self.avg_session.setFont(font5)
        self.avg_session.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.avg_session.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.avg_session_time = QLabel(self.widget_6)
        self.avg_session_time.setObjectName(u"avg_session_time")
        self.avg_session_time.setGeometry(QRect(8, 35, 211, 81))
        self.avg_session_time.setFont(font4)
        self.avg_session_time.setStyleSheet(u"border: 0px\n"
"")
        self.avg_session_time.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.graf_avg = QPushButton(self.widget_6)
        self.graf_avg.setObjectName(u"graf_avg")
        self.graf_avg.setGeometry(QRect(40, 120, 151, 24))
        self.graf_avg.setStyleSheet(u"background-color: rgb(24, 24, 24)")
        self.banned_amount = QWidget(self.general_stats)
        self.banned_amount.setObjectName(u"banned_amount")
        self.banned_amount.setGeometry(QRect(10, 490, 230, 150))
        self.banned_amount.setMaximumSize(QSize(230, 150))
        self.banned_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_27 = QLabel(self.banned_amount)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(0, 0, 231, 30))
        self.label_27.setFont(font5)
        self.label_27.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_27.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.banned_users_amount = QLabel(self.banned_amount)
        self.banned_users_amount.setObjectName(u"banned_users_amount")
        self.banned_users_amount.setGeometry(QRect(8, 35, 211, 111))
        self.banned_users_amount.setFont(font4)
        self.banned_users_amount.setStyleSheet(u"border: 0px")
        self.banned_users_amount.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.avg_pure_clicks_session = QWidget(self.general_stats)
        self.avg_pure_clicks_session.setObjectName(u"avg_pure_clicks_session")
        self.avg_pure_clicks_session.setGeometry(QRect(270, 170, 230, 150))
        self.avg_pure_clicks_session.setMaximumSize(QSize(230, 150))
        self.avg_pure_clicks_session.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_29 = QLabel(self.avg_pure_clicks_session)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(0, 0, 231, 30))
        font6 = QFont()
        font6.setPointSize(10)
        font6.setBold(False)
        self.label_29.setFont(font6)
        self.label_29.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_29.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.avg_pure_clicks = QLabel(self.avg_pure_clicks_session)
        self.avg_pure_clicks.setObjectName(u"avg_pure_clicks")
        self.avg_pure_clicks.setGeometry(QRect(8, 35, 211, 111))
        self.avg_pure_clicks.setFont(font4)
        self.avg_pure_clicks.setStyleSheet(u"border: 0px")
        self.avg_pure_clicks.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.soul_amount = QWidget(self.general_stats)
        self.soul_amount.setObjectName(u"soul_amount")
        self.soul_amount.setGeometry(QRect(270, 330, 230, 150))
        self.soul_amount.setMaximumSize(QSize(230, 150))
        self.soul_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_31 = QLabel(self.soul_amount)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(0, 0, 231, 30))
        self.label_31.setFont(font5)
        self.label_31.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_31.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.all_souls = QLabel(self.soul_amount)
        self.all_souls.setObjectName(u"all_souls")
        self.all_souls.setGeometry(QRect(8, 35, 211, 111))
        self.all_souls.setFont(font4)
        self.all_souls.setStyleSheet(u"border: 0px")
        self.all_souls.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.widget = QWidget(self.general_stats)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(530, 10, 361, 151))
        self.bottle_buy_amount = QWidget(self.widget)
        self.bottle_buy_amount.setObjectName(u"bottle_buy_amount")
        self.bottle_buy_amount.setGeometry(QRect(110, 0, 230, 150))
        self.bottle_buy_amount.setMaximumSize(QSize(230, 150))
        self.bottle_buy_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_33 = QLabel(self.bottle_buy_amount)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(0, 0, 231, 30))
        self.label_33.setFont(font3)
        self.label_33.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_33.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bottle_bought = QLabel(self.bottle_buy_amount)
        self.bottle_bought.setObjectName(u"bottle_bought")
        self.bottle_bought.setGeometry(QRect(8, 35, 211, 121))
        self.bottle_bought.setFont(font4)
        self.bottle_bought.setStyleSheet(u"border: 0px")
        self.bottle_bought.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_9 = QLabel(self.widget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(10, 40, 91, 91))
        self.label_9.setPixmap(QPixmap(u"../bottle.png"))
        self.label_9.setScaledContents(True)
        self.widget_2 = QWidget(self.general_stats)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(530, 170, 351, 151))
        self.euls_buy_amount = QWidget(self.widget_2)
        self.euls_buy_amount.setObjectName(u"euls_buy_amount")
        self.euls_buy_amount.setGeometry(QRect(110, 0, 230, 150))
        self.euls_buy_amount.setMaximumSize(QSize(230, 150))
        self.euls_buy_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_35 = QLabel(self.euls_buy_amount)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(0, 0, 231, 30))
        self.label_35.setFont(font3)
        self.label_35.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_35.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.euls_bought = QLabel(self.euls_buy_amount)
        self.euls_bought.setObjectName(u"euls_bought")
        self.euls_bought.setGeometry(QRect(8, 35, 211, 121))
        self.euls_bought.setFont(font4)
        self.euls_bought.setStyleSheet(u"border: 0px")
        self.euls_bought.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_10 = QLabel(self.widget_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(10, 40, 91, 91))
        self.label_10.setPixmap(QPixmap(u"../eul.png"))
        self.label_10.setScaledContents(True)
        self.widget_12 = QWidget(self.general_stats)
        self.widget_12.setObjectName(u"widget_12")
        self.widget_12.setGeometry(QRect(530, 330, 351, 151))
        self.blink_buy_amount = QWidget(self.widget_12)
        self.blink_buy_amount.setObjectName(u"blink_buy_amount")
        self.blink_buy_amount.setGeometry(QRect(110, 0, 230, 150))
        self.blink_buy_amount.setMaximumSize(QSize(230, 150))
        self.blink_buy_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_37 = QLabel(self.blink_buy_amount)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(0, 0, 231, 30))
        self.label_37.setFont(font3)
        self.label_37.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_37.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.blink_bought = QLabel(self.blink_buy_amount)
        self.blink_bought.setObjectName(u"blink_bought")
        self.blink_bought.setGeometry(QRect(8, 35, 211, 121))
        self.blink_bought.setFont(font4)
        self.blink_bought.setStyleSheet(u"border: 0px")
        self.blink_bought.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_39 = QLabel(self.widget_12)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(10, 40, 91, 91))
        self.label_39.setPixmap(QPixmap(u"../blink.png"))
        self.label_39.setScaledContents(True)
        self.widget_14 = QWidget(self.general_stats)
        self.widget_14.setObjectName(u"widget_14")
        self.widget_14.setGeometry(QRect(530, 490, 351, 151))
        self.bkb_buy_amount = QWidget(self.widget_14)
        self.bkb_buy_amount.setObjectName(u"bkb_buy_amount")
        self.bkb_buy_amount.setGeometry(QRect(110, 0, 230, 150))
        self.bkb_buy_amount.setMaximumSize(QSize(230, 150))
        self.bkb_buy_amount.setStyleSheet(u"background-color: rgb(45, 45, 45);\n"
"border-radius: 10px;\n"
"border: 1px solid rgb(24, 24, 24)")
        self.label_40 = QLabel(self.bkb_buy_amount)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(0, 0, 231, 30))
        self.label_40.setFont(font3)
        self.label_40.setStyleSheet(u"background-color: rgb(74, 74, 74)\n"
"\n"
"")
        self.label_40.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.bkb_bouth_amount = QLabel(self.bkb_buy_amount)
        self.bkb_bouth_amount.setObjectName(u"bkb_bouth_amount")
        self.bkb_bouth_amount.setGeometry(QRect(8, 35, 211, 121))
        self.bkb_bouth_amount.setFont(font4)
        self.bkb_bouth_amount.setStyleSheet(u"border: 0px")
        self.bkb_bouth_amount.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_42 = QLabel(self.widget_14)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(10, 40, 91, 91))
        self.label_42.setPixmap(QPixmap(u"../bkb.png"))
        self.label_42.setScaledContents(True)
        self.admin_window.addTab(self.general_stats, "")
        self.top_users = QWidget()
        self.top_users.setObjectName(u"top_users")
        self.scrollArea_3 = QScrollArea(self.top_users)
        self.scrollArea_3.setObjectName(u"scrollArea_3")
        self.scrollArea_3.setGeometry(QRect(0, 0, 971, 461))
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollAreaWidgetContents_4 = QWidget()
        self.scrollAreaWidgetContents_4.setObjectName(u"scrollAreaWidgetContents_4")
        self.scrollAreaWidgetContents_4.setGeometry(QRect(0, 0, 969, 459))
        self.verticalLayoutWidget_2 = QWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayoutWidget_2.setObjectName(u"verticalLayoutWidget_2")
        self.verticalLayoutWidget_2.setGeometry(QRect(9, -1, 931, 451))
        self.layout_scroll_3 = QVBoxLayout(self.verticalLayoutWidget_2)
        self.layout_scroll_3.setObjectName(u"layout_scroll_3")
        self.layout_scroll_3.setContentsMargins(0, 0, 0, 0)
        self.description_3 = QWidget(self.verticalLayoutWidget_2)
        self.description_3.setObjectName(u"description_3")
        self.description_3.setMaximumSize(QSize(16777215, 60))
        self.description_3.setStyleSheet(u"background-color: rgb(77, 77, 77)")
        self.horizontalLayoutWidget_3 = QWidget(self.description_3)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(-1, -3, 931, 61))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.label_43 = QLabel(self.horizontalLayoutWidget_3)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setFont(font2)
        self.label_43.setTextFormat(Qt.TextFormat.AutoText)
        self.label_43.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label_43)

        self.label_44 = QLabel(self.horizontalLayoutWidget_3)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setFont(font2)
        self.label_44.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label_44)

        self.label_45 = QLabel(self.horizontalLayoutWidget_3)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setFont(font2)
        self.label_45.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label_45)

        self.label_46 = QLabel(self.horizontalLayoutWidget_3)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setFont(font2)
        self.label_46.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_3.addWidget(self.label_46)


        self.layout_scroll_3.addWidget(self.description_3)

        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.admin_window.addTab(self.top_users, "")
        self.banned_users = QWidget()
        self.banned_users.setObjectName(u"banned_users")
        self.scrollArea_4 = QScrollArea(self.banned_users)
        self.scrollArea_4.setObjectName(u"scrollArea_4")
        self.scrollArea_4.setGeometry(QRect(0, -10, 971, 471))
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollAreaWidgetContents_5 = QWidget()
        self.scrollAreaWidgetContents_5.setObjectName(u"scrollAreaWidgetContents_5")
        self.scrollAreaWidgetContents_5.setGeometry(QRect(0, 0, 969, 469))
        self.verticalLayoutWidget_4 = QWidget(self.scrollAreaWidgetContents_5)
        self.verticalLayoutWidget_4.setObjectName(u"verticalLayoutWidget_4")
        self.verticalLayoutWidget_4.setGeometry(QRect(9, 19, 931, 431))
        self.layout_scroll_4 = QVBoxLayout(self.verticalLayoutWidget_4)
        self.layout_scroll_4.setObjectName(u"layout_scroll_4")
        self.layout_scroll_4.setContentsMargins(0, 0, 0, 0)
        self.description_4 = QWidget(self.verticalLayoutWidget_4)
        self.description_4.setObjectName(u"description_4")
        self.description_4.setMaximumSize(QSize(16777215, 60))
        self.description_4.setStyleSheet(u"background-color: rgb(77, 77, 77)")
        self.horizontalLayoutWidget_5 = QWidget(self.description_4)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(-1, -3, 931, 61))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.label_47 = QLabel(self.horizontalLayoutWidget_5)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setFont(font2)
        self.label_47.setTextFormat(Qt.TextFormat.AutoText)
        self.label_47.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_47)

        self.label_48 = QLabel(self.horizontalLayoutWidget_5)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setFont(font2)
        self.label_48.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_48)

        self.label_49 = QLabel(self.horizontalLayoutWidget_5)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setFont(font2)
        self.label_49.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_49)

        self.label_50 = QLabel(self.horizontalLayoutWidget_5)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setFont(font2)
        self.label_50.setAlignment(Qt.AlignmentFlag.AlignCenter)

        self.horizontalLayout_4.addWidget(self.label_50)


        self.layout_scroll_4.addWidget(self.description_4)

        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_5)
        self.admin_window.addTab(self.banned_users, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.admin_window.raise_()
        self.user_clicker.raise_()
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 978, 33))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        self.user_clicker.setCurrentIndex(2)
        self.admin_window.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.clicks_amount.setText(QCoreApplication.translate("MainWindow", u"\u0427\u0438\u0441\u043b\u043e", None))
        self.click_button.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.user_clicker.setTabText(self.user_clicker.indexOf(self.clicker), QCoreApplication.translate("MainWindow", u"\u041a\u043b\u0438\u043a\u0435\u0440", None))
        self.eul_pic.setText("")
        self.eul_name.setText(QCoreApplication.translate("MainWindow", u"Euls Scepter", None))
        self.eul_desc.setText(QCoreApplication.translate("MainWindow", u"+5 \u0434\u0443\u0448/\u043a\u043b\u0438\u043a     \u0426\u0435\u043d\u0430: 50 \u0434\u0443\u0448", None))
        self.eul_button.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u043f\u0438\u0442\u044c", None))
        self.bkb_pic.setText("")
        self.bkb_name.setText(QCoreApplication.translate("MainWindow", u"Black King Bar", None))
        self.bkb_desc.setText(QCoreApplication.translate("MainWindow", u"+50 \u0434\u0443\u0448/\u043a\u043b\u0438\u043a     \u0426\u0435\u043d\u0430: 1000 \u0434\u0443\u0448", None))
        self.bkb_button.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u043f\u0438\u0442\u044c", None))
        self.bottle_pic_11.setText("")
        self.bottle_name_11.setText(QCoreApplication.translate("MainWindow", u"Bottle", None))
        self.bottle_desc.setText(QCoreApplication.translate("MainWindow", u"+1 \u0434\u0443\u0448/\u043a\u043b\u0438\u043a     \u0426\u0435\u043d\u0430: 25 \u0434\u0443\u0448", None))
        self.bottle_button.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u043f\u0438\u0442\u044c", None))
        self.blink_pic.setText("")
        self.blink_name.setText(QCoreApplication.translate("MainWindow", u"Blink dagger", None))
        self.blink_desc.setText(QCoreApplication.translate("MainWindow", u"+10 \u0434\u0443\u0448/\u043a\u043b\u0438\u043a     \u0426\u0435\u043d\u0430: 100 \u0434\u0443\u0448", None))
        self.blink_button.setText(QCoreApplication.translate("MainWindow", u"\u041a\u0443\u043f\u0438\u0442\u044c", None))
        self.user_clicker.setTabText(self.user_clicker.indexOf(self.magazin), QCoreApplication.translate("MainWindow", u"\u041c\u0430\u0433\u0430\u0437\u0438\u043d", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0435\u0441\u0442\u043e", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b-\u0432\u043e \u0434\u0443\u0448", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0443\u0448 \u0437\u0430 \u043a\u043b\u0438\u043a", None))
        self.user_clicker.setTabText(self.user_clicker.indexOf(self.user), QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u0430", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"\u041f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439", None))
        self.us_amount.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.graf_users.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"\u0427\u0438\u0441\u0442\u044b\u0445 \u043a\u043b\u0438\u043a\u043e\u0432", None))
        self.pure_clicks_amount.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"\u0422\u0435\u043a\u0443\u0449\u0438\u0439 \u043e\u043d\u043b\u0430\u0439\u043d", None))
        self.now_online.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.graf_online.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430", None))
        self.avg_session.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0440\u0435\u0434\u043d\u044f\u044f \u0434\u043b\u0438\u0442\u0435\u043b\u044c\u043d\u043e\u0441\u0442\u044c \u0441\u0435\u0441\u0441\u0438\u0438", None))
        self.avg_session_time.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.graf_avg.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0431\u0430\u043d\u0435\u043d\u043d\u044b\u0445 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439", None))
        self.banned_users_amount.setText(QCoreApplication.translate("MainWindow", u"0", None))
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"\u0421\u0440\u0435\u0434\u043d\u0435\u0435 \u0447\u0438\u0441\u043b\u043e \u043a\u043b\u0438\u043a\u043e\u0432 \u0437\u0430 \u0441\u0435\u0441\u0441\u0438\u044e", None))
        self.avg_pure_clicks.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"\u041e\u0431\u0449\u0435\u0435 \u043a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u0434\u0443\u0448", None))
        self.all_souls.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_33.setText(QCoreApplication.translate("MainWindow", u"Bottle \u043a\u0443\u043f\u043b\u0435\u043d\u043e", None))
        self.bottle_bought.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_9.setText("")
        self.label_35.setText(QCoreApplication.translate("MainWindow", u"Euls \u043a\u0443\u043f\u043b\u0435\u043d\u043e", None))
        self.euls_bought.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_10.setText("")
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"Blink \u043a\u0443\u043f\u043b\u0435\u043d\u043e", None))
        self.blink_bought.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_39.setText("")
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Bkb \u043a\u0443\u043f\u043b\u0435\u043d\u043e", None))
        self.bkb_bouth_amount.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_42.setText("")
        self.admin_window.setTabText(self.admin_window.indexOf(self.general_stats), QCoreApplication.translate("MainWindow", u"\u041e\u0431\u0449\u0430\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0430", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"\u041c\u0435\u0441\u0442\u043e", None))
        self.label_44.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f", None))
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"\u041a\u043e\u043b-\u0432\u043e \u0434\u0443\u0448", None))
        self.label_46.setText(QCoreApplication.translate("MainWindow", u"\u0414\u0443\u0448 \u0437\u0430 \u043a\u043b\u0438\u043a", None))
        self.admin_window.setTabText(self.admin_window.indexOf(self.top_users), QCoreApplication.translate("MainWindow", u"\u0422\u043e\u043f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0435\u0439", None))
        self.label_47.setText(QCoreApplication.translate("MainWindow", u"ID \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f", None))
        self.label_48.setText(QCoreApplication.translate("MainWindow", u"\u0418\u043c\u044f \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f", None))
        self.label_49.setText(QCoreApplication.translate("MainWindow", u"\u0412\u0440\u0435\u043c\u044f \u0431\u0430\u043d\u0430", None))
        self.label_50.setText(QCoreApplication.translate("MainWindow", u"\u0410\u043f\u043f\u0435\u043b\u044f\u0446\u0438\u044f", None))
        self.admin_window.setTabText(self.admin_window.indexOf(self.banned_users), QCoreApplication.translate("MainWindow", u"\u0417\u0430\u0431\u0430\u043d\u0435\u043d\u043d\u044b\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u0438", None))
    # retranslateUi

